<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="Techno-311" failures="0" tests="8" name="io.mosip.testscripts.DemoAuth" time="8.490" errors="4" timestamp="31 Jan 2023 07:46:23 GMT" skipped="0">
  <testcase classname="io.mosip.testscripts.DemoAuth" name="auth_EkycDemo_Auth_With_blocked_VID" time="1.090"/>
  <testcase classname="io.mosip.testscripts.DemoAuth" name="auth_EkycDemo_Auth_With_blocked_UIN_Pos" time="0.982">
    <error message="Failed at output validation" type="io.mosip.admin.fw.util.AdminTestException">
      <![CDATA[io.mosip.admin.fw.util.AdminTestException: Failed at output validation
	at io.mosip.testscripts.DemoAuth.test(DemoAuth.java:140)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:869)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1193)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:375)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1226)
	at org.testng.TestNG.runSuites(TestNG.java:1144)
	at org.testng.TestNG.run(TestNG.java:1115)
	at io.mosip.testrunner.MosipTestRunner.startTestRunner(MosipTestRunner.java:177)
	at io.mosip.testrunner.MosipTestRunner.main(MosipTestRunner.java:124)
]]>
    </error>
  </testcase> <!-- auth_EkycDemo_Auth_With_blocked_UIN_Pos -->
  <testcase classname="io.mosip.testscripts.DemoAuth" name="auth_DemoAuth_Locked_UIN_Pos" time="1.024">
    <error message="Failed at output validation" type="io.mosip.admin.fw.util.AdminTestException">
      <![CDATA[io.mosip.admin.fw.util.AdminTestException: Failed at output validation
	at io.mosip.testscripts.DemoAuth.test(DemoAuth.java:140)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:869)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1193)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:375)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1226)
	at org.testng.TestNG.runSuites(TestNG.java:1144)
	at org.testng.TestNG.run(TestNG.java:1115)
	at io.mosip.testrunner.MosipTestRunner.startTestRunner(MosipTestRunner.java:177)
	at io.mosip.testrunner.MosipTestRunner.main(MosipTestRunner.java:124)
]]>
    </error>
  </testcase> <!-- auth_DemoAuth_Locked_UIN_Pos -->
  <testcase classname="io.mosip.testscripts.DemoAuth" name="auth_DemoAuth_blocked_partnerid_Pos" time="1.084"/>
  <testcase classname="io.mosip.testscripts.DemoAuth" name="auth_DemoAuth_blocked_VID_Pos" time="1.009"/>
  <testcase classname="io.mosip.testscripts.DemoAuth" name="auth_DemoAuth_blocked_UIN_Pos" time="1.160">
    <error message="Failed at output validation" type="io.mosip.admin.fw.util.AdminTestException">
      <![CDATA[io.mosip.admin.fw.util.AdminTestException: Failed at output validation
	at io.mosip.testscripts.DemoAuth.test(DemoAuth.java:140)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:869)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1193)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:375)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1226)
	at org.testng.TestNG.runSuites(TestNG.java:1144)
	at org.testng.TestNG.run(TestNG.java:1115)
	at io.mosip.testrunner.MosipTestRunner.startTestRunner(MosipTestRunner.java:177)
	at io.mosip.testrunner.MosipTestRunner.main(MosipTestRunner.java:124)
]]>
    </error>
  </testcase> <!-- auth_DemoAuth_blocked_UIN_Pos -->
  <testcase classname="io.mosip.testscripts.DemoAuth" name="auth_EkycDemo_Auth_With_blocked_VID" time="1.087"/>
  <testcase classname="io.mosip.testscripts.DemoAuth" name="auth_EkycDemo_Auth_With_blocked_UIN_Pos" time="1.054">
    <error message="Failed at output validation" type="io.mosip.admin.fw.util.AdminTestException">
      <![CDATA[io.mosip.admin.fw.util.AdminTestException: Failed at output validation
	at io.mosip.testscripts.DemoAuth.test(DemoAuth.java:140)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:869)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1193)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:375)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1226)
	at org.testng.TestNG.runSuites(TestNG.java:1144)
	at org.testng.TestNG.run(TestNG.java:1115)
	at io.mosip.testrunner.MosipTestRunner.startTestRunner(MosipTestRunner.java:177)
	at io.mosip.testrunner.MosipTestRunner.main(MosipTestRunner.java:124)
]]>
    </error>
  </testcase> <!-- auth_EkycDemo_Auth_With_blocked_UIN_Pos -->
</testsuite> <!-- io.mosip.testscripts.DemoAuth -->
