<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="Techno-311" failures="1" tests="1" name="AuditLogUploadCertificate_FTP" time="0.015" errors="0" timestamp="14 Jul 2023 17:03:00 GMT">
  <testcase classname="io.mosip.testscripts.AuditValidator" name="@AfterMethod setResultTestName" time="0.006">
    <failure type="java.lang.AssertionError" message="Exception in getting the session expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: Exception in getting the session expected [true] but found [false]
	at io.mosip.dbaccess.AuditDBManager.getDataBaseConnection(AuditDBManager.java:137)
	at io.mosip.dbaccess.AuditDBManager.executeQueryAndDeleteRecord(AuditDBManager.java:83)
	at io.mosip.testscripts.AuditValidator.setResultTestName(AuditValidator.java:105)
	at io.mosip.testrunner.MosipTestRunner.startTestRunner(MosipTestRunner.java:161)
	at io.mosip.testrunner.MosipTestRunner.main(MosipTestRunner.java:114)
... Removed 26 stack frames]]>
    </failure>
  </testcase> <!-- @AfterMethod setResultTestName -->
  <testcase classname="io.mosip.testscripts.AuditValidator" name="" time="0.005">
    <failure type="java.lang.AssertionError" message="Exception in getting the session expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: Exception in getting the session expected [true] but found [false]
	at io.mosip.dbaccess.AuditDBManager.getDataBaseConnection(AuditDBManager.java:137)
	at io.mosip.dbaccess.AuditDBManager.executeQueryAndGetRecord(AuditDBManager.java:43)
	at io.mosip.testscripts.AuditValidator.test(AuditValidator.java:73)
	at io.mosip.testrunner.MosipTestRunner.startTestRunner(MosipTestRunner.java:161)
	at io.mosip.testrunner.MosipTestRunner.main(MosipTestRunner.java:114)
... Removed 24 stack frames]]>
    </failure>
  </testcase> <!--  -->
</testsuite> <!-- AuditLogUploadCertificate_FTP -->
