<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="Techno-311" failures="2" tests="3" name="HotlistTestcasesAuth" time="3.205" errors="0" timestamp="31 Jan 2023 07:36:13 GMT">
  <testcase classname="io.mosip.testscripts.DemoAuth" name="" time="1.16">
    <failure type="io.mosip.admin.fw.util.AdminTestException" message="Failed at output validation">
      <![CDATA[io.mosip.admin.fw.util.AdminTestException: Failed at output validation
	at io.mosip.testscripts.DemoAuth.test(DemoAuth.java:140)
	at io.mosip.testrunner.MosipTestRunner.startTestRunner(MosipTestRunner.java:177)
	at io.mosip.testrunner.MosipTestRunner.main(MosipTestRunner.java:124)
... Removed 22 stack frames]]>
    </failure>
  </testcase> <!--  -->
  <testcase classname="io.mosip.testscripts.DemoAuth" name="auth_DemoAuth_blocked_UIN_Pos" time="1.023">
    <failure type="io.mosip.admin.fw.util.AdminTestException" message="Failed at output validation">
      <![CDATA[io.mosip.admin.fw.util.AdminTestException: Failed at output validation
	at io.mosip.testscripts.DemoAuth.test(DemoAuth.java:140)
	at io.mosip.testrunner.MosipTestRunner.startTestRunner(MosipTestRunner.java:177)
	at io.mosip.testrunner.MosipTestRunner.main(MosipTestRunner.java:124)
... Removed 22 stack frames]]>
    </failure>
  </testcase> <!-- auth_DemoAuth_blocked_UIN_Pos -->
  <testcase classname="io.mosip.testscripts.DemoAuth" name="auth_DemoAuth_Locked_UIN_Pos" time="1.009"/>
</testsuite> <!-- HotlistTestcasesAuth -->
